.IMAGE 软件架构
.IMAGE 分层架构
.IMAGE 微服务
.IMAGE 单体架构
.IMAGE 事件驱动架构
.IMAGE 事件总线
.IMAGE 事件溯源
.IMAGE CQRS
.IMAGE Saga
.IMAGE 分布式事务
.IMAGE 最终一致性
.IMAGE DDD
.IMAGE 限界上下文
.IMAGE 聚合
.IMAGE 领域事件
.IMAGE 充血模型
.IMAGE 贫血模型
.IMAGE 防腐层
.IMAGE 依赖倒置
.IMAGE 依赖注入
.IMAGE 低耦合
.IMAGE 模块化
.IMAGE 高内聚
.IMAGE 断路器
.IMAGE 可靠性
.IMAGE 网关
.IMAGE 服务发现
.IMAGE 配置中心
.IMAGE 幂等
.IMAGE 消息队列
.IMAGE 单一职责
.IMAGE 开闭原则
.IMAGE 可扩展性
.IMAGE 接口隔离
.IMAGE 架构演进
.IMAGE 技术债
.IMAGE 架构评审
.IMAGE 可维护性
.IMAGE 可预测性
.FIELD ARCH
.FIELD 模式
.FIELD 事件
.FIELD 分布式
.FIELD DDD
.FIELD 原则
.FIELD 云模式
.FIELD 集成
.FIELD SOLID
.FIELD 方法
.FIELD 价值
SUPPORT 软件架构 分层架构 .WEIGHT 0.800 .FIELD ARCH
SUPPORT 软件架构 微服务 .WEIGHT 0.700 .FIELD ARCH
BUT 微服务 单体架构 .WEIGHT 0.600 .FIELD 模式
IF 事件驱动架构 事件总线 .WEIGHT 0.800 .FIELD 事件
SUPPORT 事件溯源 事件驱动架构 .WEIGHT 0.800 .FIELD 事件
SUPPORT CQRS 事件驱动架构 .WEIGHT 0.800 .FIELD 事件
UNDERMINE Saga 分布式事务 .WEIGHT 0.700 .FIELD 分布式
SUPPORT Saga 最终一致性 .WEIGHT 0.700 .FIELD 分布式
ENTAIL DDD 限界上下文 .WEIGHT 0.900 .FIELD DDD
SUPPORT 限界上下文 聚合 .WEIGHT 0.800 .FIELD DDD
IF 聚合 领域事件 .WEIGHT 0.700 .FIELD DDD
SUPPORT 领域事件 事件驱动架构 .WEIGHT 0.700 .FIELD DDD
SUPPORT 充血模型 DDD .WEIGHT 0.800 .FIELD DDD
BUT 贫血模型 充血模型 .WEIGHT 0.600 .FIELD DDD
SUPPORT 防腐层 限界上下文 .WEIGHT 0.700 .FIELD DDD
SUPPORT 依赖倒置 依赖注入 .WEIGHT 0.800 .FIELD 原则
SUPPORT 依赖注入 低耦合 .WEIGHT 0.800 .FIELD 原则
SUPPORT 模块化 低耦合 .WEIGHT 0.800 .FIELD 原则
SUPPORT 模块化 高内聚 .WEIGHT 0.800 .FIELD 原则
SUPPORT 断路器 可靠性 .WEIGHT 0.800 .FIELD 云模式
SUPPORT 网关 微服务 .WEIGHT 0.700 .FIELD 云模式
SUPPORT 服务发现 微服务 .WEIGHT 0.700 .FIELD 云模式
SUPPORT 配置中心 微服务 .WEIGHT 0.700 .FIELD 云模式
SUPPORT 幂等 可靠性 .WEIGHT 0.800 .FIELD 分布式
SUPPORT 消息队列 低耦合 .WEIGHT 0.700 .FIELD 集成
SUPPORT 单一职责 高内聚 .WEIGHT 0.800 .FIELD SOLID
SUPPORT 开闭原则 可扩展性 .WEIGHT 0.800 .FIELD SOLID
SUPPORT 接口隔离 低耦合 .WEIGHT 0.700 .FIELD SOLID
UNDERMINE 架构演进 技术债 .WEIGHT 0.600 .FIELD 方法
UNDERMINE 架构评审 技术债 .WEIGHT 0.600 .FIELD 方法
UNDERMINE 技术债 可维护性 .WEIGHT 0.700 .FIELD 方法
SUPPORT 可扩展性 可维护性 .WEIGHT 0.600 .FIELD 价值
SUPPORT 可靠性 可预测性 .WEIGHT 0.600 .FIELD 价值