.IMAGE 网络安全
.IMAGE 威胁建模
.IMAGE 攻击面
.IMAGE 漏洞
.IMAGE 安全
.IMAGE 漏洞扫描
.IMAGE 渗透测试
.IMAGE 红队
.IMAGE 蓝队
.IMAGE 事件响应
.IMAGE SQL注入
.IMAGE XSS
.IMAGE CSRF
.IMAGE SSRF
.IMAGE 命令注入
.IMAGE 越权
.IMAGE 认证
.IMAGE 授权
.IMAGE OAuth
.IMAGE JWT
.IMAGE 多因素认证
.IMAGE 最小权限
.IMAGE RBAC
.IMAGE ABAC
.IMAGE 对称加密
.IMAGE 加密
.IMAGE 非对称加密
.IMAGE 哈希
.IMAGE 数字签名
.IMAGE 密钥管理
.IMAGE TLS
.IMAGE 传输加密
.IMAGE 证书
.IMAGE Web防火墙
.IMAGE 入侵检测
.IMAGE 安全事件
.IMAGE 入侵防御
.IMAGE 沙箱
.IMAGE 安全日志
.IMAGE 应急响应
.IMAGE 数字取证
.IMAGE 数据泄露
.IMAGE 数据脱敏
.IMAGE 数据分类
.IMAGE 隐私合规
.IMAGE GDPR
.IMAGE 安全审计
.IMAGE 合规
.IMAGE 安全测试
.IMAGE 模糊测试
.IMAGE 供应链安全
.IMAGE 软件成分分析
.IMAGE 零信任
.IMAGE 纵深防御
.IMAGE 安全基线
.IMAGE 威胁情报
.IMAGE 安全编码
.IMAGE 安全测试自动化
.IMAGE DevSecOps
.IMAGE 可靠性
.IMAGE 安全运营中心
.IMAGE 蜜罐
.IMAGE 端点检测
.IMAGE 测试
.IMAGE 缺陷
.IMAGE 可维护性
.IMAGE 代码可读性
.FIELD SEC
.FIELD 方法论
.FIELD 威胁
.FIELD 检测
.FIELD 防御
.FIELD 攻击
.FIELD 身份
.FIELD 授权
.FIELD 密码学
.FIELD 传输
.FIELD 响应
.FIELD 风险
.FIELD 数据
.FIELD 合规
.FIELD 测试
.FIELD 供应链
.FIELD 架构
.FIELD 情报
.FIELD 开发
.FIELD 价值
.FIELD 运营
.FIELD 质量
IF 网络安全 威胁建模 .WEIGHT 0.800 .FIELD SEC
SUPPORT 威胁建模 攻击面 .WEIGHT 0.700 .FIELD 方法论
IF 攻击面 漏洞 .WEIGHT 0.700 .FIELD 威胁
UNDERMINE 漏洞 安全 .WEIGHT 0.900 .FIELD 威胁
IF 漏洞扫描 漏洞 .WEIGHT 0.700 .FIELD 检测
IF 渗透测试 漏洞 .WEIGHT 0.800 .FIELD 检测
SUPPORT 红队 渗透测试 .WEIGHT 0.800 .FIELD 检测
SUPPORT 蓝队 事件响应 .WEIGHT 0.800 .FIELD 防御
LIKE SQL注入 漏洞 .WEIGHT 0.800 .FIELD 攻击
LIKE XSS 漏洞 .WEIGHT 0.800 .FIELD 攻击
LIKE CSRF 漏洞 .WEIGHT 0.700 .FIELD 攻击
LIKE SSRF 漏洞 .WEIGHT 0.700 .FIELD 攻击
LIKE 命令注入 漏洞 .WEIGHT 0.700 .FIELD 攻击
LIKE 越权 漏洞 .WEIGHT 0.700 .FIELD 攻击
SUPPORT 认证 安全 .WEIGHT 0.800 .FIELD 身份
SUPPORT 授权 安全 .WEIGHT 0.800 .FIELD 身份
SUPPORT OAuth 认证 .WEIGHT 0.800 .FIELD 身份
SUPPORT JWT 认证 .WEIGHT 0.700 .FIELD 身份
SUPPORT 多因素认证 认证 .WEIGHT 0.800 .FIELD 身份
SUPPORT 最小权限 安全 .WEIGHT 0.900 .FIELD 身份
SUPPORT RBAC 授权 .WEIGHT 0.800 .FIELD 授权
SUPPORT ABAC 授权 .WEIGHT 0.700 .FIELD 授权
BELONG 对称加密 加密 .WEIGHT 0.800 .FIELD 密码学
BELONG 非对称加密 加密 .WEIGHT 0.800 .FIELD 密码学
SUPPORT 哈希 加密 .WEIGHT 0.700 .FIELD 密码学
SUPPORT 数字签名 非对称加密 .WEIGHT 0.800 .FIELD 密码学
SUPPORT 密钥管理 加密 .WEIGHT 0.800 .FIELD 密码学
SUPPORT TLS 传输加密 .WEIGHT 0.800 .FIELD 传输
IF 证书 TLS .WEIGHT 0.800 .FIELD 传输
UNDERMINE Web防火墙 SQL注入 .WEIGHT 0.600 .FIELD 防御
UNDERMINE Web防火墙 XSS .WEIGHT 0.600 .FIELD 防御
IF 入侵检测 安全事件 .WEIGHT 0.700 .FIELD 防御
SUPPORT 入侵防御 入侵检测 .WEIGHT 0.700 .FIELD 防御
SUPPORT 沙箱 安全 .WEIGHT 0.600 .FIELD 防御
SUPPORT 安全日志 入侵检测 .WEIGHT 0.700 .FIELD 检测
IF 安全事件 事件响应 .WEIGHT 0.800 .FIELD 响应
SUPPORT 应急响应 事件响应 .WEIGHT 0.800 .FIELD 响应
SUPPORT 数字取证 事件响应 .WEIGHT 0.700 .FIELD 响应
UNDERMINE 数据泄露 安全 .WEIGHT 0.800 .FIELD 风险
UNDERMINE 数据脱敏 数据泄露 .WEIGHT 0.700 .FIELD 数据
IF 数据分类 数据脱敏 .WEIGHT 0.700 .FIELD 数据
IF 隐私合规 数据脱敏 .WEIGHT 0.700 .FIELD 合规
SUPPORT GDPR 隐私合规 .WEIGHT 0.800 .FIELD 合规
SUPPORT 安全审计 合规 .WEIGHT 0.800 .FIELD 合规
UNDERMINE 安全测试 漏洞 .WEIGHT 0.700 .FIELD 测试
SUPPORT 模糊测试 安全测试 .WEIGHT 0.700 .FIELD 测试
SUPPORT 供应链安全 软件成分分析 .WEIGHT 0.800 .FIELD 供应链
UNDERMINE 软件成分分析 漏洞 .WEIGHT 0.700 .FIELD 供应链
SUPPORT 零信任 安全 .WEIGHT 0.800 .FIELD 架构
SUPPORT 纵深防御 安全 .WEIGHT 0.800 .FIELD 架构
SUPPORT 安全基线 纵深防御 .WEIGHT 0.700 .FIELD 架构
UNDERMINE 威胁情报 漏洞 .WEIGHT 0.600 .FIELD 情报
UNDERMINE 安全编码 漏洞 .WEIGHT 0.800 .FIELD 开发
SUPPORT 安全测试自动化 安全测试 .WEIGHT 0.800 .FIELD 开发
SUPPORT DevSecOps 安全测试自动化 .WEIGHT 0.800 .FIELD 开发
SUPPORT 安全 可靠性 .WEIGHT 0.700 .FIELD 价值
IF 安全运营中心 安全事件 .WEIGHT 0.700 .FIELD 运营
SUPPORT 蜜罐 威胁情报 .WEIGHT 0.600 .FIELD 运营
SUPPORT 端点检测 入侵检测 .WEIGHT 0.700 .FIELD 运营
UNDERMINE 测试 缺陷 .WEIGHT 0.600 .FIELD 质量
SUPPORT 可维护性 代码可读性 .WEIGHT 0.600 .FIELD 价值