.IMAGE LLM应用
.IMAGE Prompt工程
.IMAGE 幻觉
.IMAGE RAG
.IMAGE 向量检索
.IMAGE 向量数据库
.IMAGE Embedding
.IMAGE 知识库
.IMAGE 文档解析
.IMAGE 分块
.IMAGE 重排序
.IMAGE 准确性
.IMAGE 混合检索
.IMAGE 上下文窗口
.IMAGE Token管理
.IMAGE 成本控制
.IMAGE 工具调用
.IMAGE Agent
.IMAGE 多轮对话
.IMAGE 人机回环
.IMAGE 数据管道
.IMAGE 数据清洗
.IMAGE 数据质量
.IMAGE 特征工程
.IMAGE 模型训练
.IMAGE 过拟合
.IMAGE 欠拟合
.IMAGE 模型评估
.IMAGE 数据漂移
.IMAGE MLOps
.IMAGE 模型版本管理
.IMAGE 模型注册表
.IMAGE 实验追踪
.IMAGE 可解释性
.IMAGE A/B测试
.IMAGE 可观测性
.IMAGE 缓存
.IMAGE 延迟
.IMAGE 批处理
.IMAGE 吞吐量
.IMAGE 流式输出
.IMAGE 隐私合规
.IMAGE 数据脱敏
.IMAGE 提示注入
.IMAGE 越狱攻击
.IMAGE 内容审核
.IMAGE 标注
.IMAGE 微调
.IMAGE 少样本学习
.IMAGE 评估指标
.IMAGE 基准集
.IMAGE 反馈收集
.IMAGE 可靠性
.IMAGE 测试
.IMAGE 缺陷
.IMAGE 单元测试
.IMAGE 回归
.IMAGE 数据管道调度
.IMAGE 血缘追踪
.IMAGE 特征存储
.IMAGE 在线推理
.IMAGE 批量推理
.IMAGE 性能瓶颈
.IMAGE 数据湖
.IMAGE 可维护性
.IMAGE 代码可读性
.FIELD LLM
.FIELD RAG
.FIELD 数据
.FIELD ML
.FIELD 工程
.FIELD 性能
.FIELD 安全
.FIELD 价值
.FIELD 质量
IF LLM应用 Prompt工程 .WEIGHT 0.800 .FIELD LLM
UNDERMINE Prompt工程 幻觉 .WEIGHT 0.600 .FIELD LLM
UNDERMINE RAG 幻觉 .WEIGHT 0.700 .FIELD LLM
SUPPORT RAG 向量检索 .WEIGHT 0.800 .FIELD LLM
IF 向量检索 向量数据库 .WEIGHT 0.800 .FIELD LLM
IF Embedding 向量检索 .WEIGHT 0.800 .FIELD LLM
IF 知识库 RAG .WEIGHT 0.800 .FIELD RAG
SUPPORT 文档解析 知识库 .WEIGHT 0.700 .FIELD RAG
IF 分块 向量检索 .WEIGHT 0.700 .FIELD RAG
SUPPORT 重排序 准确性 .WEIGHT 0.700 .FIELD RAG
SUPPORT 混合检索 准确性 .WEIGHT 0.600 .FIELD RAG
IF 上下文窗口 Token管理 .WEIGHT 0.800 .FIELD LLM
SUPPORT Token管理 成本控制 .WEIGHT 0.700 .FIELD LLM
SUPPORT 工具调用 Agent .WEIGHT 0.800 .FIELD LLM
IF 多轮对话 上下文窗口 .WEIGHT 0.700 .FIELD LLM
IF Agent 人机回环 .WEIGHT 0.600 .FIELD LLM
SUPPORT 数据管道 数据清洗 .WEIGHT 0.800 .FIELD 数据
SUPPORT 数据清洗 数据质量 .WEIGHT 0.800 .FIELD 数据
SUPPORT 数据质量 准确性 .WEIGHT 0.800 .FIELD 数据
IF 特征工程 模型训练 .WEIGHT 0.800 .FIELD ML
UNDERMINE 过拟合 准确性 .WEIGHT 0.700 .FIELD ML
UNDERMINE 欠拟合 准确性 .WEIGHT 0.700 .FIELD ML
IF 模型评估 过拟合 .WEIGHT 0.700 .FIELD ML
UNDERMINE 数据漂移 准确性 .WEIGHT 0.700 .FIELD ML
SUPPORT MLOps 模型版本管理 .WEIGHT 0.800 .FIELD 工程
SUPPORT 模型版本管理 模型注册表 .WEIGHT 0.700 .FIELD 工程
SUPPORT 实验追踪 可解释性 .WEIGHT 0.700 .FIELD 工程
SUPPORT A/B测试 可观测性 .WEIGHT 0.700 .FIELD 工程
UNDERMINE 缓存 延迟 .WEIGHT 0.700 .FIELD 性能
SUPPORT 批处理 吞吐量 .WEIGHT 0.600 .FIELD 性能
UNDERMINE 流式输出 延迟 .WEIGHT 0.600 .FIELD 性能
IF 隐私合规 数据脱敏 .WEIGHT 0.700 .FIELD 安全
SUPPORT 数据脱敏 隐私合规 .WEIGHT 0.700 .FIELD 安全
SUPPORT 提示注入 越狱攻击 .WEIGHT 0.800 .FIELD 安全
UNDERMINE 内容审核 越狱攻击 .WEIGHT 0.600 .FIELD 安全
SUPPORT 标注 数据质量 .WEIGHT 0.700 .FIELD 数据
SUPPORT 微调 准确性 .WEIGHT 0.600 .FIELD ML
BUT 少样本学习 微调 .WEIGHT 0.500 .FIELD ML
IF 评估指标 模型评估 .WEIGHT 0.800 .FIELD ML
SUPPORT 基准集 评估指标 .WEIGHT 0.700 .FIELD ML
SUPPORT 反馈收集 人机回环 .WEIGHT 0.700 .FIELD ML
SUPPORT 可解释性 可靠性 .WEIGHT 0.600 .FIELD 价值
SUPPORT 准确性 可靠性 .WEIGHT 0.800 .FIELD 价值
UNDERMINE 测试 缺陷 .WEIGHT 0.600 .FIELD 质量
BELONG 单元测试 测试 .WEIGHT 0.700 .FIELD 质量
UNDERMINE 回归 准确性 .WEIGHT 0.600 .FIELD 质量
SUPPORT 数据管道调度 数据管道 .WEIGHT 0.700 .FIELD 工程
SUPPORT 血缘追踪 可解释性 .WEIGHT 0.600 .FIELD 数据
SUPPORT 特征存储 特征工程 .WEIGHT 0.700 .FIELD ML
IF 在线推理 延迟 .WEIGHT 0.600 .FIELD ML
SUPPORT 批量推理 吞吐量 .WEIGHT 0.600 .FIELD ML
IF LLM应用 成本控制 .WEIGHT 0.600 .FIELD LLM
LIKE 性能瓶颈 延迟 .WEIGHT 0.600 .FIELD 性能
SUPPORT 数据湖 数据管道 .WEIGHT 0.600 .FIELD 数据
SUPPORT 可维护性 代码可读性 .WEIGHT 0.600 .FIELD 价值