.IMAGE 操作系统
.IMAGE 进程
.IMAGE 线程
.IMAGE 协程
.IMAGE 调度器
.IMAGE 上下文切换
.IMAGE 上下文切换开销
.IMAGE 互斥
.IMAGE 死锁
.IMAGE 信号量
.IMAGE 条件变量
.IMAGE 可靠性
.IMAGE 虚拟内存
.IMAGE 分页
.IMAGE 页面置换
.IMAGE 内存映射
.IMAGE 文件系统
.IMAGE inode
.IMAGE 文件描述符
.IMAGE I/O多路复用
.IMAGE select
.IMAGE epoll
.IMAGE 阻塞I/O
.IMAGE I/O模型
.IMAGE 非阻塞I/O
.IMAGE 异步I/O
.IMAGE 系统调用
.IMAGE 内核态
.IMAGE 用户态
.IMAGE 管道
.IMAGE 进程间通信
.IMAGE 共享内存
.IMAGE 消息队列
.IMAGE 套接字
.IMAGE 僵尸进程
.IMAGE 缺陷
.IMAGE 资源泄漏
.IMAGE OOMKiller
.IMAGE CPU占用
.IMAGE 性能瓶颈
.IMAGE 内存占用
.IMAGE 磁盘I/O
.IMAGE NUMA
.IMAGE 负载均衡
.IMAGE 测试
.IMAGE 可预测性
.FIELD OS
.FIELD 并发
.FIELD 同步
.FIELD 内存
.FIELD 存储
.FIELD IO
.FIELD 接口
.FIELD IPC
.FIELD 问题
.FIELD 性能
.FIELD 调度
.FIELD 质量
.FIELD 价值
ENTAIL 操作系统 进程 .WEIGHT 0.900 .FIELD OS
SUPPORT 进程 线程 .WEIGHT 0.800 .FIELD 并发
SUPPORT 线程 协程 .WEIGHT 0.700 .FIELD 并发
IF 调度器 上下文切换 .WEIGHT 0.900 .FIELD 并发
CAUSE 上下文切换 上下文切换开销 .WEIGHT 0.800 .FIELD 并发
CAUSE 互斥 死锁 .WEIGHT 0.600 .FIELD 同步
SUPPORT 信号量 互斥 .WEIGHT 0.700 .FIELD 同步
SUPPORT 条件变量 线程 .WEIGHT 0.700 .FIELD 同步
UNDERMINE 死锁 可靠性 .WEIGHT 0.700 .FIELD 同步
IF 虚拟内存 分页 .WEIGHT 0.900 .FIELD 内存
IF 分页 页面置换 .WEIGHT 0.800 .FIELD 内存
SUPPORT 内存映射 虚拟内存 .WEIGHT 0.700 .FIELD 内存
IF 文件系统 inode .WEIGHT 0.800 .FIELD 存储
SUPPORT 文件描述符 文件系统 .WEIGHT 0.700 .FIELD 存储
BELONG I/O多路复用 select .WEIGHT 0.700 .FIELD IO
BELONG I/O多路复用 epoll .WEIGHT 0.800 .FIELD IO
SUPPORT epoll I/O多路复用 .WEIGHT 0.800 .FIELD IO
BELONG 阻塞I/O I/O模型 .WEIGHT 0.800 .FIELD IO
BELONG 非阻塞I/O I/O模型 .WEIGHT 0.800 .FIELD IO
BELONG 异步I/O I/O模型 .WEIGHT 0.800 .FIELD IO
IF 系统调用 内核态 .WEIGHT 0.900 .FIELD 接口
BUT 用户态 内核态 .WEIGHT 0.600 .FIELD 接口
BELONG 管道 进程间通信 .WEIGHT 0.800 .FIELD IPC
BELONG 共享内存 进程间通信 .WEIGHT 0.800 .FIELD IPC
BELONG 消息队列 进程间通信 .WEIGHT 0.800 .FIELD IPC
BELONG 套接字 进程间通信 .WEIGHT 0.800 .FIELD IPC
LIKE 僵尸进程 缺陷 .WEIGHT 0.600 .FIELD 问题
UNDERMINE 资源泄漏 可靠性 .WEIGHT 0.700 .FIELD 问题
UNDERMINE OOMKiller 可靠性 .WEIGHT 0.600 .FIELD 问题
CAUSE CPU占用 性能瓶颈 .WEIGHT 0.800 .FIELD 性能
CAUSE 内存占用 性能瓶颈 .WEIGHT 0.800 .FIELD 性能
CAUSE 磁盘I/O 性能瓶颈 .WEIGHT 0.700 .FIELD 性能
CAUSE 上下文切换开销 性能瓶颈 .WEIGHT 0.700 .FIELD 性能
SUPPORT NUMA 负载均衡 .WEIGHT 0.600 .FIELD 调度
UNDERMINE 测试 缺陷 .WEIGHT 0.600 .FIELD 质量
SUPPORT 可靠性 可预测性 .WEIGHT 0.600 .FIELD 价值