.FIELD 场景
.IMAGE DSL设计决策
SUPPORT DSL设计决策 领域特定语言 .WEIGHT 0.7 .FIELD 场景
SUPPORT DSL设计决策 语义模型 .WEIGHT 0.5 .FIELD 场景
SUPPORT DSL设计决策 学习成本 .WEIGHT 0.5 .FIELD 场景
.IMAGE 内嵌DSL实现
SUPPORT 内嵌DSL实现 类型安全DSL .WEIGHT 0.5 .FIELD 场景
SUPPORT 内嵌DSL实现 组合性 .WEIGHT 0.5 .FIELD 场景
.IMAGE 外部DSL实现
SUPPORT 外部DSL实现 AST .WEIGHT 0.5 .FIELD 场景
.IMAGE 元编程应用
SUPPORT 元编程应用 元编程 .WEIGHT 0.7 .FIELD 场景
SUPPORT 元编程应用 宏 .WEIGHT 0.7 .FIELD 场景
SUPPORT 元编程应用 反射 .WEIGHT 0.7 .FIELD 场景
SUPPORT 元编程应用 代码生成 .WEIGHT 0.7 .FIELD 场景
SUPPORT 元编程应用 宏 .WEIGHT 0.5 .FIELD 场景
SUPPORT 元编程应用 反射 .WEIGHT 0.5 .FIELD 场景
SUPPORT 元编程应用 注解处理 .WEIGHT 0.5 .FIELD 场景
SUPPORT 元编程应用 代码生成 .WEIGHT 0.5 .FIELD 场景
.IMAGE 代码生成实践
SUPPORT 代码生成实践 代码生成 .WEIGHT 0.7 .FIELD 场景
.IMAGE DSL演进与维护