.IMAGE 数据库
.IMAGE 关系型数据库
.IMAGE NoSQL
.IMAGE SQL
.IMAGE ACID
.IMAGE CAP定理
.IMAGE 文档数据库
.IMAGE 键值存储
.IMAGE 列式存储
.IMAGE 图数据库
.IMAGE 索引
.IMAGE 慢查询
.IMAGE 执行计划
.IMAGE 查询优化
.IMAGE 性能瓶颈
.IMAGE 事务
.IMAGE 隔离级别
.IMAGE 数据一致性
.IMAGE 锁
.IMAGE 死锁
.IMAGE 乐观锁
.IMAGE 悲观锁
.IMAGE 主从复制
.IMAGE 读写分离
.IMAGE 吞吐量
.IMAGE 分库分表
.IMAGE 数据分片
.IMAGE 分区表
.IMAGE 可扩展性
.IMAGE 分布式事务
.IMAGE 两阶段提交
.IMAGE 最终一致性
.IMAGE 数据建模
.IMAGE 范式
.IMAGE 反范式
.IMAGE 外键
.IMAGE 数据完整性
.IMAGE 数据迁移
.IMAGE Schema变更
.IMAGE 缺陷
.IMAGE 备份
.IMAGE 恢复
.IMAGE 容灾
.IMAGE 高可用
.IMAGE 闪回
.IMAGE 连接池
.IMAGE 延迟
.IMAGE 缓存
.IMAGE 缓存穿透
.IMAGE 缓存击穿
.IMAGE 缓存雪崩
.IMAGE Redis
.IMAGE 消息队列
.IMAGE 数据同步
.IMAGE 变更数据捕获
.IMAGE 数据仓库
.IMAGE ETL
.IMAGE 数据质量
.IMAGE 数据湖
.IMAGE 数据脱敏
.IMAGE 数据加密
.IMAGE 安全
.IMAGE 访问控制
.IMAGE 审计
.IMAGE 故障切换
.IMAGE 可靠性
.IMAGE 测试
.FIELD DB
.FIELD 查询
.FIELD 一致性
.FIELD 并发
.FIELD 架构
.FIELD 理论
.FIELD 设计
.FIELD 运维
.FIELD 性能
.FIELD 缓存
.FIELD 集成
.FIELD 分析
.FIELD 安全
.FIELD 质量
SUPPORT 数据库 关系型数据库 .WEIGHT 0.700 .FIELD DB
SUPPORT 数据库 NoSQL .WEIGHT 0.600 .FIELD DB
ENTAIL 关系型数据库 SQL .WEIGHT 0.900 .FIELD DB
IF 关系型数据库 ACID .WEIGHT 0.800 .FIELD DB
IF NoSQL CAP定理 .WEIGHT 0.700 .FIELD DB
BELONG 文档数据库 NoSQL .WEIGHT 0.800 .FIELD DB
BELONG 键值存储 NoSQL .WEIGHT 0.800 .FIELD DB
BELONG 列式存储 NoSQL .WEIGHT 0.800 .FIELD DB
BELONG 图数据库 NoSQL .WEIGHT 0.800 .FIELD DB
UNDERMINE 索引 慢查询 .WEIGHT 0.800 .FIELD 查询
IF 执行计划 慢查询 .WEIGHT 0.700 .FIELD 查询
SUPPORT 查询优化 执行计划 .WEIGHT 0.800 .FIELD 查询
CAUSE 慢查询 性能瓶颈 .WEIGHT 0.800 .FIELD 查询
SUPPORT 事务 ACID .WEIGHT 0.800 .FIELD 一致性
IF 隔离级别 数据一致性 .WEIGHT 0.700 .FIELD 一致性
CAUSE 锁 死锁 .WEIGHT 0.600 .FIELD 并发
BELONG 乐观锁 锁 .WEIGHT 0.700 .FIELD 并发
BELONG 悲观锁 锁 .WEIGHT 0.700 .FIELD 并发
CAUSE 死锁 性能瓶颈 .WEIGHT 0.700 .FIELD 并发
SUPPORT 主从复制 读写分离 .WEIGHT 0.800 .FIELD 架构
SUPPORT 读写分离 吞吐量 .WEIGHT 0.700 .FIELD 架构
SUPPORT 分库分表 数据分片 .WEIGHT 0.800 .FIELD 架构
SUPPORT 分区表 数据分片 .WEIGHT 0.700 .FIELD 架构
SUPPORT 数据分片 可扩展性 .WEIGHT 0.700 .FIELD 架构
CAUSE 数据分片 分布式事务 .WEIGHT 0.600 .FIELD 架构
UNDERMINE 分布式事务 数据一致性 .WEIGHT 0.700 .FIELD 一致性
SUPPORT 两阶段提交 分布式事务 .WEIGHT 0.600 .FIELD 一致性
SUPPORT 最终一致性 数据一致性 .WEIGHT 0.600 .FIELD 一致性
SUPPORT CAP定理 最终一致性 .WEIGHT 0.600 .FIELD 理论
IF 数据建模 范式 .WEIGHT 0.700 .FIELD 设计
BUT 反范式 范式 .WEIGHT 0.600 .FIELD 设计
SUPPORT 外键 数据完整性 .WEIGHT 0.800 .FIELD 设计
SUPPORT 数据迁移 Schema变更 .WEIGHT 0.800 .FIELD 运维
CAUSE Schema变更 缺陷 .WEIGHT 0.500 .FIELD 运维
IF 备份 恢复 .WEIGHT 0.800 .FIELD 运维
SUPPORT 备份 容灾 .WEIGHT 0.700 .FIELD 运维
SUPPORT 恢复 高可用 .WEIGHT 0.700 .FIELD 运维
SUPPORT 闪回 恢复 .WEIGHT 0.600 .FIELD 运维
UNDERMINE 连接池 延迟 .WEIGHT 0.600 .FIELD 性能
UNDERMINE 缓存 延迟 .WEIGHT 0.700 .FIELD 性能
CAUSE 缓存穿透 性能瓶颈 .WEIGHT 0.700 .FIELD 性能
CAUSE 缓存击穿 性能瓶颈 .WEIGHT 0.700 .FIELD 性能
CAUSE 缓存雪崩 性能瓶颈 .WEIGHT 0.800 .FIELD 性能
SUPPORT Redis 缓存 .WEIGHT 0.800 .FIELD 缓存
SUPPORT 消息队列 数据同步 .WEIGHT 0.700 .FIELD 集成
SUPPORT 变更数据捕获 数据同步 .WEIGHT 0.800 .FIELD 集成
IF 数据仓库 ETL .WEIGHT 0.800 .FIELD 分析
SUPPORT ETL 数据质量 .WEIGHT 0.700 .FIELD 分析
LIKE 数据湖 数据仓库 .WEIGHT 0.500 .FIELD 分析
SUPPORT 数据脱敏 数据质量 .WEIGHT 0.600 .FIELD 安全
SUPPORT 数据加密 安全 .WEIGHT 0.800 .FIELD 安全
SUPPORT 访问控制 安全 .WEIGHT 0.800 .FIELD 安全
SUPPORT 审计 安全 .WEIGHT 0.700 .FIELD 安全
SUPPORT 故障切换 高可用 .WEIGHT 0.800 .FIELD 架构
SUPPORT 容灾 高可用 .WEIGHT 0.800 .FIELD 架构
SUPPORT 高可用 可靠性 .WEIGHT 0.800 .FIELD 架构
SUPPORT 数据完整性 可靠性 .WEIGHT 0.700 .FIELD 质量
UNDERMINE 测试 缺陷 .WEIGHT 0.600 .FIELD 质量